name: CI-CD Pipeline (Demo)

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build step (simulate)
        run: echo "Building application..."

      - name: Test step (simulate)
        run: echo "Running tests..."

      - name: Deploy step (simulate)
        run: echo "Deploying application to server 🚀"
